## University of Southern California 


**Fall 2020: EE510**

**Date:** Friday, August 28th, 2020

### Discussion Session 1: Introduction to Python/Numpy: Quick start

**Section 1: Installation Guide**<br>

In this section we will go over a guide to install Python, however, the installation is actually straight-forward. I recommend downloading Jupyter and Python with the Anaconda Distribution. <br>

**1-** Go to the [Anaconda Installation](https://docs.anaconda.com/anaconda/install/) page and click on the Graphical Installer for your system to download the installer. <br>

**2-** Follow the directions for the graphical installer you chose. <br>

**3-** After downloading Anaconda you can begin with the installation commands for Jupyter. All installation commands should be run in the Terminal (for Mac and Linux) or the Command Prompt/Powershell (Windows). You can install Jupyter Notebooks by just click install in the Anaconda Navigator or you can go to your terminal/command prompt and type **conda install jupyter**. Note that in general Jupyter Notebooks is installed by default. <br>

**4-** You should eventually see a new tab open up in your browser for you to begin using Jupyter Notebooks. <br>

**5-** For more information on the Jupyter Notebook system in general, check out the official documentation. <br>

**Section 2: Basic Topics**<br>

In this section, we will go through the basic topics in Python in order:

* Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Booleans
    * Sets
* Comparison Operators
* if, elif, else Statements
* for Loops
* while Loops
* range()
* list comprehension
* functions
* methods

## Data types

### Numbers

In [1]:
1 + 1

2

The result is 2

In [2]:
2 * 3

6

In [3]:
1 / 2

0.5

In [4]:
2 ** 3

8

In [5]:
6 % 3

0

In [6]:
7 % 3

1

### Variable Assignment

In [7]:
var = 4

In [8]:
type(var)

int

### Strings

In [9]:
' EE 510 '

' EE 510 '

In [10]:
" EE 510 "

' EE 510 '

In [11]:
" The class's website is Piazza "

" The class's website is Piazza "

### Printing

In [12]:
cls = 'EE 510'

In [13]:
type(cls)

str

In [14]:
cls

'EE 510'

In [15]:
print (cls)

EE 510


In [16]:
cls_1 = 'EE'
ID = 510
print('This class is in the {dpt} department and its id is {id}'.format(dpt=cls_1,id=ID))

This class is in the EE department and its id is 510


### Lists

In [17]:
l = [1,2,3]

In [18]:
type(l)

list

In [19]:
my_list = ['EE510',1,[1,2]]

In [20]:
my_list [0]

'EE510'

In [21]:
my_list [2]

[1, 2]

In [22]:
my_list.append(['Hello', 'World'])
my_list

['EE510', 1, [1, 2], ['Hello', 'World']]

In [23]:
my_list [-1]

['Hello', 'World']

In [24]:
my_list [3][1]

'World'

In [25]:
my_list [3][1][2]

'r'

### Booleans

In [26]:
True

True

In [27]:
False

False

In [28]:
True and False

False

In [29]:
True or False

True

### Sets

In [30]:
my_set = {1,2,3}
my_set

{1, 2, 3}

In [31]:
1 in my_set 

True

In [32]:
4 in my_set

False

## Comparison Operators

In [33]:
1 > 2

False

In [34]:
1 < 2

True

In [35]:
2 >= 2

True

In [36]:
3 <= 4

True

In [37]:
1 == 1

True

In [38]:
'Hello' == 'Bye'

False

## Logic Operators

In [39]:
(1 > 2) and (2 < 3)

False

In [40]:
(1 >= 2) or (2 >= 3) or (1 == 1)

True

## if,elif, else Statements

In [41]:
if 1 < 4:
    print('Valid')

Valid


In [42]:
x = 2
y = 2
if x < y:
    print('y is greater than x')
elif x == y:
    print('x is equal to y')
else:
    print('x is greater than y')

x is equal to y


## for Loops

In [43]:
my_list = [1, 2, 3, 4, 5]
for ele in my_list:
    print(ele)

1
2
3
4
5


## while Loops

In [44]:
i = 1
while i < 6:
    print('The current index i is: {}'.format(i))
    i = i+1

The current index i is: 1
The current index i is: 2
The current index i is: 3
The current index i is: 4
The current index i is: 5


## range()

In [45]:
range(5)

range(0, 5)

In [46]:
for index in range(5):
    print(index)

0
1
2
3
4


In [47]:
list(range(5))

[0, 1, 2, 3, 4]

## list comprehension

In [48]:
# compute the square elements of the following list
my_list = [1,2,3,4]

output = []
for ele in my_list:
    output.append(ele**2)
print(output)

[1, 4, 9, 16]


In [49]:
[ele**2 for ele in my_list]

[1, 4, 9, 16]

## functions

In [50]:
def square(x):
    """
    Calculate the square of x.
    """
    return(x**2)

In [51]:
value = square(2)
print(value)

4


## methods

In [52]:
msg = 'Hello, this class is EE510'
print(msg)

Hello, this class is EE510


In [53]:
msg.lower()

'hello, this class is ee510'

In [54]:
msg.upper()

'HELLO, THIS CLASS IS EE510'

In [55]:
msg.split()

['Hello,', 'this', 'class', 'is', 'EE510']

In [56]:
msg_1 = 'Hello, %this class is %EE510'
print(msg_1)

Hello, %this class is %EE510


In [57]:
msg_1.split('%')

['Hello, ', 'this class is ', 'EE510']

**Section 3: NumPy**<br>
NumPy (or Numpy) is a Linear Algebra Library for Python, it is one of the most important libraries for Python. NumPy has many built-in functions and capabilities. In this section, We will learn the basics of NumPy by focusing on some of the most important aspects of Numpy: vectors, arrays, matrices..

## Installation Instructions

As mentioned earlier, it is highly recommended you install Python using the Anaconda distribution. To install NumPy in Anaconda, go to your terminal or command prompt and typing: 

    conda install numpy

## Using NumPy

After installing NumPy you can import it as a library:

In [58]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially are vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

## Creating NumPy Arrays

### From a Python List
We can create an array by directly converting a list or list of lists:

In [59]:
my_lst = [2,4,6]

In [60]:
np.array(my_lst)

array([2, 4, 6])

In [61]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
type(my_matrix)

numpy.ndarray

In [64]:
my_matrix.shape

(3, 3)

## Built-in Methods

### arange

In [65]:
# Return evenly spaced values within a given interval.
vect_1 = np.arange(0,15)
vect_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
vect_2 = np.arange(0,13,2)
vect_2

array([ 0,  2,  4,  6,  8, 10, 12])

### zeros and ones
Generate arrays of zeros or ones

In [67]:
np.zeros(4)

array([0., 0., 0., 0.])

In [68]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
np.ones(4)

array([1., 1., 1., 1.])

In [70]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [71]:
np.linspace(0,15,5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [72]:
np.linspace(0,20,9)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

## eye

Creates an identity matrix

In [73]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape whose entries are sampled from the uniform distribution over the interval ``[0, 1)``.

In [74]:
np.random.rand(3)

array([0.95184349, 0.60458422, 0.75331223])

In [75]:
np.random.rand(3,5)

array([[0.24953249, 0.69319515, 0.13698404, 0.68814158, 0.04740076],
       [0.79961932, 0.44316425, 0.6101734 , 0.85784254, 0.401028  ],
       [0.54315329, 0.79855414, 0.8482636 , 0.74633383, 0.93302172]])

### randn

Return an array sample of the given shape whose entries are sampled from the standard normal distribution.

In [76]:
np.random.randn(3)

array([ 0.51138136, -1.43366315,  0.46202698])

In [77]:
np.random.randn(3,5)

array([[ 1.1526241 ,  1.38825005,  0.81968303, -1.03154564, -0.46015249],
       [-0.30655333, -1.254469  , -0.06625151, -0.29415699,  0.8039562 ],
       [-1.86038791, -1.22363321,  0.56220066, -0.6473561 , -2.0417781 ]])

### randint
Return an array sample of the given shape whose entries are random integers from `low` (inclusive) to `high` (exclusive).

In [78]:
np.random.randint(1,10)

9

In [79]:
np.random.randint(1,10,[3,5])

array([[8, 8, 5, 3, 7],
       [5, 2, 7, 7, 2],
       [4, 3, 8, 1, 2]])

## Array Attributes and Methods

In [80]:
my_vect = np.arange(30)
my_vect

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
my_matrix = my_vect.reshape(5,6)
my_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [82]:
my_matrix.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [83]:
np.linalg.det(np.random.rand(5,5))

-0.06033988894742718

In [84]:
np.linalg.matrix_rank(np.random.rand(5,5))

5

In [85]:
my_matrix.max()

29

In [86]:
my_matrix.argmax()

29

In [87]:
my_matrix.min()

0

In [88]:
my_matrix.argmin()

0

In [89]:
my_matrix.dtype

dtype('int64')

## Indexing and Data Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [90]:
my_vect = np.arange(20)
my_vect

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [91]:
# get a value at an index
my_vect[10]

10

In [92]:
# get values in a range
my_vect[3:9]

array([3, 4, 5, 6, 7, 8])

In [93]:
my_vect[-1]

19

In [94]:
# Important notes
my_vect = np.arange(15)
my_vect

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [95]:
slice_my_vect = my_vect [0:7]
slice_my_vect

array([0, 1, 2, 3, 4, 5, 6])

In [96]:
slice_my_vect[:] = 20
slice_my_vect

array([20, 20, 20, 20, 20, 20, 20])

In [97]:
my_vect

array([20, 20, 20, 20, 20, 20, 20,  7,  8,  9, 10, 11, 12, 13, 14])

** The changes also occur in our original array !!** The array is not copied, it is a view of the original array. To make a copy of the orginal array:

In [98]:
my_vect = np.arange(15)
my_vect_copy = my_vect[0:7].copy()
my_vect_copy

array([0, 1, 2, 3, 4, 5, 6])

## Indexing a 2D array (matrices)

In [99]:
my_vect = np.arange(30)
my_matrix = my_vect.reshape(5,6)
my_matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [100]:
# indexing row
my_matrix[1]

array([ 6,  7,  8,  9, 10, 11])

In [101]:
# indexing column
my_matrix[:,1]

array([ 1,  7, 13, 19, 25])

In [102]:
# getting an individual element 
my_matrix[1][0]

6

In [103]:
# matrix slicing
my_matrix[:3,2:]

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17]])

## Selection

In [104]:
my_vect = np.arange(1,16)
my_vect

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [105]:
my_vect > 7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True])

In [106]:
bool_vect = my_vect > 7

In [107]:
bool_vect

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True])

In [108]:
my_vect[bool_vect]

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [109]:
# find all the elements greater than a given value x
x = 3
my_vect[my_vect > x]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [110]:
# find the index of the first element in an array that is greater than x
index = np.where(my_vect == my_vect[my_vect > x][0])
index[0][0]

3

In [111]:
my_vect = np.arange(1,10)
my_vect

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
# the np.where is used to find an index of a given element in an array
x = 4
index = np.where(my_vect == x)
# the returned result "index" is an array storing all the indices of elements equal to x
# we get the first index of element with value equal to x using: 
index[0][0]

3

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:


In [113]:
vect = np.arange(0,6)
vect + vect

array([ 0,  2,  4,  6,  8, 10])

In [114]:
vect * vect

array([ 0,  1,  4,  9, 16, 25])

In [115]:
vect - vect

array([0, 0, 0, 0, 0, 0])

In [116]:
# warning on dividing by 0 (not an error)
vect / vect

/Users/mohamedridhaznaidi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.])

In [117]:
# warning 
1 / vect

/Users/mohamedridhaznaidi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

In [118]:
vect**2

array([ 0,  1,  4,  9, 16, 25])

## Universal Array Functions

NumPy comes with many other [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (i.e., mathematical operations can be applied to a given array).

In [119]:
# taking Square Roots
np.sqrt(vect)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [120]:
# calcualting exponential
np.exp(vect)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [121]:
np.sin(vect)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [122]:
np.log(vect[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [123]:
A = np.array([[1, 0],
              [0, 1]])
A

array([[1, 0],
       [0, 1]])

In [124]:
B = np.array([[4, 1],
              [2, 2]])
B

array([[4, 1],
       [2, 2]])

In [125]:
np.matmul(A,B)

array([[4, 1],
       [2, 2]])

You can also find additional universal [linear algebra functions](https://numpy.org/doc/stable/reference/routines.linalg.html).

# Thank you !